import React from 'react';
import P from 'prop-types';
import Header from './_components/Header';
import Footer from './_components/Footer';
import { QueryContext } from './queryContext';
import StyleProvider from '@/app/styleProvider';
import GlobalStyles from '@/app/styles/globalStyles';
import montserrat from '@/app/styles/font';

export const metadata = {
  title: 'Mayak!',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <StyleProvider>
          <GlobalStyles />
          <Header />
          <QueryContext>{children}</QueryContext>
          <Footer />
        </StyleProvider>
      </body>
    </html>
  );
}

RootLayout.propTypes = {
  children: P.node.isRequired,
};
